version: '3.3'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: booking_api
      MYSQL_ROOT_PASSWORD: root
      
    volumes:
      - my-db:/var/lib/
      - ./mysql-files:/var/lib/mysql-files
    networks:
      app_net:
        ipv4_address: 172.16.238.10
      
  admin-microservice:
    container_name: admin-microservice
    #build: Dockerfile
    image: admin_microservice:latest
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    ports:
        - 7070:10000
        
  login-microservice:
    container_name: login-microservice
    image: login_microservice:latest
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    ports:
        - 6060:10001

  grpc-server:
    container_name: grpc-server
    image: grpc_server:latest
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.13
    ports:
        - 50051:50051   
  
# Names our volume
volumes:
  my-db:
